services:
  switchinfo:
    build: ./switchinfo_docker
    restart: unless-stopped
    container_name: switchinfo
    command: gunicorn switchinfo_docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - config_backup_volume:/home/config_backup
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

#    environment:
#    - DEFAULT_REPOSITORY_DIR = /home/config_backup

  gitlist:
    build: ./gitlist
    restart: unless-stopped
    volumes:
    # - gitlist_volume:/var/www/html
    # - config_backup_volume:/home/config_backup
    #- config_backup_volume:/home/config_backup
    - static_volume:/var/www/html/static
    - media_volume:/var/www/html/media
    - config_backup_volume:/var/www/Config
    ports:
    - "1337:80"
#    environment:
#    - DEFAULT_REPOSITORY_DIR = /home/config_backup

#    networks:
#    - internal



volumes:
  postgres_data:
  static_volume:
  media_volume:
  gitlist_volume:
  config_backup_volume:

networks:
  internal:
    driver: bridge
